export class Colombia_respuesta {
    constructor(
        public idrespuesta: number,
        public autorizacion: string,
        public referencia: string,
        public recibo: string,
        public nombre_entidad: string,
        public codigo: string,
        public monto: string,
        public banco: string,
        public estado_transaccion: string,
        public codigo_retorno: string,
        public ip: string,
        public fecha: string,
        public marca: string,
        public correo: string,
        public tipo_documento: string,
        public documento: string,
        public nombres: string,
        public apellidos: string,
        public direccion: string,
        public telefono: string,
        public celular: string,
        public ciudad: string,
        public provincia: string,
        public pais: string,
        public descripcion_producto: string,
        public referencia_producto: string,
        public cantidad_producto: string,
        public idioma: string,
        public mensaje_respuesta: string,
        public codigo_respuesta: string,
        public mensaje: string,
        public monto_inicial: string,
        public moneda: string,
        public descripcion_pago: string
    ) { }
} 